/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { JSONSchemaObject } from "@json-schema-tools/meta-schema";
export { JSONSchemaObject } from "@json-schema-tools/meta-schema";
export namespace Components {
    interface JsonSchemaUi {
        "path"?: string;
        "schema": string;
    }
    interface JsonSchemaUiArray {
        "keyName": string;
        "schema": JSONSchemaObject;
    }
}
declare global {
    interface HTMLJsonSchemaUiElement extends Components.JsonSchemaUi, HTMLStencilElement {
    }
    var HTMLJsonSchemaUiElement: {
        prototype: HTMLJsonSchemaUiElement;
        new (): HTMLJsonSchemaUiElement;
    };
    interface HTMLJsonSchemaUiArrayElement extends Components.JsonSchemaUiArray, HTMLStencilElement {
    }
    var HTMLJsonSchemaUiArrayElement: {
        prototype: HTMLJsonSchemaUiArrayElement;
        new (): HTMLJsonSchemaUiArrayElement;
    };
    interface HTMLElementTagNameMap {
        "json-schema-ui": HTMLJsonSchemaUiElement;
        "json-schema-ui-array": HTMLJsonSchemaUiArrayElement;
    }
}
declare namespace LocalJSX {
    interface JsonSchemaUi {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        "path"?: string;
        "schema"?: string;
    }
    interface JsonSchemaUiArray {
        "keyName"?: string;
        "schema"?: JSONSchemaObject;
    }

    interface JsonSchemaUiAttributes {
        "schema": string;
        "path": string;
    }
    interface JsonSchemaUiArrayAttributes {
        "keyName": string;
    }

    interface IntrinsicElements {
        "json-schema-ui": Omit<JsonSchemaUi, keyof JsonSchemaUiAttributes> & { [K in keyof JsonSchemaUi & keyof JsonSchemaUiAttributes]?: JsonSchemaUi[K] } & { [K in keyof JsonSchemaUi & keyof JsonSchemaUiAttributes as `attr:${K}`]?: JsonSchemaUiAttributes[K] } & { [K in keyof JsonSchemaUi & keyof JsonSchemaUiAttributes as `prop:${K}`]?: JsonSchemaUi[K] };
        "json-schema-ui-array": Omit<JsonSchemaUiArray, keyof JsonSchemaUiArrayAttributes> & { [K in keyof JsonSchemaUiArray & keyof JsonSchemaUiArrayAttributes]?: JsonSchemaUiArray[K] } & { [K in keyof JsonSchemaUiArray & keyof JsonSchemaUiArrayAttributes as `attr:${K}`]?: JsonSchemaUiArrayAttributes[K] } & { [K in keyof JsonSchemaUiArray & keyof JsonSchemaUiArrayAttributes as `prop:${K}`]?: JsonSchemaUiArray[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "json-schema-ui": LocalJSX.IntrinsicElements["json-schema-ui"] & JSXBase.HTMLAttributes<HTMLJsonSchemaUiElement>;
            "json-schema-ui-array": LocalJSX.IntrinsicElements["json-schema-ui-array"] & JSXBase.HTMLAttributes<HTMLJsonSchemaUiArrayElement>;
        }
    }
}
