/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { JSONSchemaObject } from "@json-schema-tools/meta-schema";
export { JSONSchemaObject } from "@json-schema-tools/meta-schema";
export namespace Components {
    interface JsonWizard {
        "schema": string;
    }
    interface JsonWizardArray {
        "name": string;
        "schema": JSONSchemaObject;
    }
}
declare global {
    interface HTMLJsonWizardElement extends Components.JsonWizard, HTMLStencilElement {
    }
    var HTMLJsonWizardElement: {
        prototype: HTMLJsonWizardElement;
        new (): HTMLJsonWizardElement;
    };
    interface HTMLJsonWizardArrayElement extends Components.JsonWizardArray, HTMLStencilElement {
    }
    var HTMLJsonWizardArrayElement: {
        prototype: HTMLJsonWizardArrayElement;
        new (): HTMLJsonWizardArrayElement;
    };
    interface HTMLElementTagNameMap {
        "json-wizard": HTMLJsonWizardElement;
        "json-wizard-array": HTMLJsonWizardArrayElement;
    }
}
declare namespace LocalJSX {
    interface JsonWizard {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        "schema"?: string;
    }
    interface JsonWizardArray {
        "name"?: string;
        "schema"?: JSONSchemaObject;
    }

    interface JsonWizardAttributes {
        "schema": string;
    }
    interface JsonWizardArrayAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "json-wizard": Omit<JsonWizard, keyof JsonWizardAttributes> & { [K in keyof JsonWizard & keyof JsonWizardAttributes]?: JsonWizard[K] } & { [K in keyof JsonWizard & keyof JsonWizardAttributes as `attr:${K}`]?: JsonWizardAttributes[K] } & { [K in keyof JsonWizard & keyof JsonWizardAttributes as `prop:${K}`]?: JsonWizard[K] };
        "json-wizard-array": Omit<JsonWizardArray, keyof JsonWizardArrayAttributes> & { [K in keyof JsonWizardArray & keyof JsonWizardArrayAttributes]?: JsonWizardArray[K] } & { [K in keyof JsonWizardArray & keyof JsonWizardArrayAttributes as `attr:${K}`]?: JsonWizardArrayAttributes[K] } & { [K in keyof JsonWizardArray & keyof JsonWizardArrayAttributes as `prop:${K}`]?: JsonWizardArray[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "json-wizard": LocalJSX.IntrinsicElements["json-wizard"] & JSXBase.HTMLAttributes<HTMLJsonWizardElement>;
            "json-wizard-array": LocalJSX.IntrinsicElements["json-wizard-array"] & JSXBase.HTMLAttributes<HTMLJsonWizardArrayElement>;
        }
    }
}
